### ISSUE TITLE
Parsing error with V1 json

### ISSUE THREAD

**Issue by thinkcontext** [USDepartmentofLabor/Ruby_DOLDataSDK#4]
Example http://api.dol.gov/V1/Safety/Fatalities/OSHA_Fatalities for id 50 the description field has a double quote character in it.   It seems the issue is the server is providing bad JSON.  I'm guessing this is a known issue since the provided example mentions dealing with such errors.  Maybe instead of just catching the error and bailing, this library could instead parse the XML which appears to be well formatted.

**Comment by MikePulsiferDOL** [comment]
While working on a dog-fooding project, we've seen this as well and have an update that we will be releasing soon.

**Comment by neilneyman** [comment]
The Ruby SDK has been updated.  For now it will return an XML object when using APIv1 (i.e. api.dol.gov urls).  JSON is still the default when using the other APIs.
